language: php

sudo: false

matrix:
    include:
        - php: 5.5
          env: deps=low
        - php: 5.6
          env: deps=low
        - php: 5.6
        - php: 7
        - php: 7.1
    fast_finish: true

before_script:
  - if [ "$deps" == "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-source; fi

script: composer test
